^^^
`catch` and `finally` are only valid in `try` context